import {useEffect,useState} from 'react'
import type {TravelPreferences} from '../api/types'
interface Props {onChange:(preferences:TravelPreferences,remember:boolean)=>void}
export function PreferencesPanel({onChange}:Props){
 const [preferences,setPreferences]=useState<TravelPreferences>({})
 const [remember,setRemember]=useState(false)
 const [message,setMessage]=useState('')
 useEffect(()=>{fetch('/api/v1/preferences').then(r=>r.json()).then(d=>{const loaded=Object.fromEntries(Object.entries(d.preferences).filter(([,v])=>v!==null&&(!Array.isArray(v)||v.length>0))) as TravelPreferences;setPreferences(loaded);onChange(loaded,false)}).catch(()=>setMessage('偏好暂时无法读取'))},[])
 function change(p:TravelPreferences){setPreferences(p);onChange(p,remember)}
 async function save(){try{const r=await fetch('/api/v1/preferences',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({preferences,remember_preferences:remember})});if(!r.ok)throw new Error();setMessage(remember?'偏好已保存到本地':'本次使用，未写入长期记忆')}catch{setMessage('偏好保存失败，请重试')}}
 async function clear(){try{const r=await fetch('/api/v1/preferences/clear',{method:'POST'});if(!r.ok)throw new Error();setPreferences({});setRemember(false);onChange({},false);setMessage('长期偏好已清除')}catch{setMessage('清除失败，请重试')}}
 const chips=[preferences.travel_pace?({'relaxed':'慢节奏','balanced':'适中','compact':'紧凑'}[preferences.travel_pace]??preferences.travel_pace):null,...(preferences.interests??[]).map(v=>({'history':'历史','night_view':'夜景','nature':'自然'}[v]??v)),preferences.avoid_early_departure?'避免早班':null,...(preferences.accommodation_preferences??[]).map(v=>({'near_metro':'靠近地铁','close_to_main_pois':'靠近景点','near_station':'靠近车站'}[v]??v))].filter(Boolean)
 return <details className="preferences-panel"><summary><strong>旅行偏好</strong><span className="preference-chips">{chips.length?chips.map(v=><span className="preference-chip" key={v}>{v}</span>):<span className="muted">尚未保存旅行偏好</span>}</span><span className="preference-edit">设置偏好</span></summary><div className="preferences-grid">
  <label>旅行节奏<select aria-label="旅行节奏" value={preferences.travel_pace??''} onChange={e=>change({...preferences,travel_pace:e.target.value||null})}><option value="">未指定</option><option value="relaxed">慢游</option><option value="balanced">适中</option><option value="compact">紧凑</option></select></label>
  <label>交通偏好<select aria-label="交通偏好" value={preferences.transport_preference??''} onChange={e=>change({...preferences,transport_preference:e.target.value||null})}><option value="">未指定</option><option value="high_speed_rail">高铁</option><option value="flight">飞机</option><option value="no_preference">均可</option></select></label>
  <label>步行接受度<select aria-label="步行接受度" value={preferences.walking_tolerance??''} onChange={e=>change({...preferences,walking_tolerance:e.target.value||null})}><option value="">未指定</option><option value="low">较少</option><option value="medium">适中</option><option value="high">较多</option></select></label>
  <label><input type="checkbox" checked={preferences.avoid_early_departure??false} onChange={e=>change({...preferences,avoid_early_departure:e.target.checked})}/>避免早班</label>
  <fieldset><legend>兴趣</legend>{[['history','历史'],['night_view','夜景'],['nature','自然']].map(([value,label])=><label key={value}><input type="checkbox" checked={preferences.interests?.includes(value)??false} onChange={e=>change({...preferences,interests:e.target.checked?[...(preferences.interests??[]),value]:(preferences.interests??[]).filter(x=>x!==value)})}/>{label}</label>)}</fieldset>
  <fieldset><legend>住宿偏好</legend>{[['near_metro','近地铁'],['close_to_main_pois','近景点'],['near_station','近车站']].map(([value,label])=><label key={value}><input type="checkbox" checked={preferences.accommodation_preferences?.includes(value)??false} onChange={e=>change({...preferences,accommodation_preferences:e.target.checked?[...(preferences.accommodation_preferences??[]),value]:(preferences.accommodation_preferences??[]).filter(x=>x!==value)})}/>{label}</label>)}</fieldset>
 </div><div className="preference-actions"><label><input type="checkbox" checked={remember} onChange={e=>{setRemember(e.target.checked);onChange(preferences,e.target.checked)}}/>记住我的偏好</label><button onClick={save}>保存偏好</button><button onClick={clear}>清除偏好</button><span role="status">{message}</span></div><p className="fine-print">仅保存结构化偏好到本机；本次明确要求优先。不开启记忆时仅用于当前请求。</p></details>
}
