export interface Issue {type:string;severity:"info"|"warning"|"error";status:"confirmed"|"unverified"|"informational";blocking:boolean;activity_id?:string|null;target?:string|null;source:string;evidence:Record<string,unknown>;message:string;suggestion:string;day:number|null}
export type Status = 'queued'|'running'|'needs_clarification'|'completed'|'partial'|'conflict'|'failed'|'cancelled'
export interface Place {id:string;name:string;city:string;coordinates:{longitude:number;latitude:number;system:string}|null}
export interface POI extends Place {category:string;environment:string;ticket_price:number|null;tags:string[];evidence_id:string}
export interface RailLeg {train_no:string;origin_station:Place;destination_station:Place;departure_time:string;arrival_time:string;duration:number;price:number|null;availability:string;evidence_id:string}
export interface Route {id:string;origin:Place;destination:Place;mode:string;duration:number;distance:number;price:number|null;evidence_id:string}
export interface DayWeather {city:string;forecast_date:string;weather_condition:string|null;min_temperature:number|null;max_temperature:number|null;precipitation?:number|null;precipitation_probability?:number|null;source:string;status:'live'|'pending'|'simulated'}
export interface Day {weather?:DayWeather|null;notes?:string[];breaks?:{label:string;start:string;end:string}[];flight?:{flight_no:string;origin_airport:Place;destination_airport:Place;departure_time:string;arrival_time:string;duration_minutes:number;provider_mode:string}|null;day:number;date:string;city:string;origin_city:string;rail:{id:string;direct:boolean;legs:RailLeg[];transfer_minutes:number[]}|null;activities:{poi:POI;start:string;end:string;time_period?:string;estimated_duration?:number;route_from_previous?:Route|null;travel_minutes?:number|null;source?:string;optional?:boolean;notes?:string[]}[];local_legs:{route:Route;departure:string;arrival:string}[];costs:{id:string;category:string;amount:number|null;label:string;source:string}[];estimated_cost:number}
export interface Itinerary {version:number;title:string;days:Day[];costs:{known_cost?:number;estimated_cost?:number;unknown_cost_items?:string[];budget_limit?:number|null;categories:Record<string,number>;estimated_total:number;unknown_items:string[];budget:number|null;delta:number|null};assumptions:string[];warnings:string[]}
export interface Trace {sequence:number;agent:string;status:string;summary:string;timestamp:string;duration_ms:number;itinerary_version:number}
export interface Evidence {id:string;provider:string;source_kind:string;notes:string;retrieved_at:string;valid_for:string[]}
export interface Constraint {travel_pace?:string;avoid_early_departure?:boolean;end_date?:string;origin?:string;destinations?:string[];days?:number;start_date?:string;total_budget?:number;preferences?:string[]}
export interface ProviderStatus {state:"LIVE"|"MOCK"|"DATASET"|"PENDING"|"FAILED"|"UNCONFIGURED";model?:string|null;error_code?:string|null}
export interface RuntimeState {memory?:{state:string};mcp:{state:string;tools:string[]};a2a:{transport:string;local:string};harness:{state:string;policy:Record<string,number>;failure_reason?:string|null;elapsed_ms?:number;tool_calls?:number;external_calls?:number}}
export interface Run {session_id?:string;memory?:{state:string;preferences:TravelPreferences};accommodation?:Accommodation[];transport_comparisons?:Comparison[];runtime_status?:RuntimeState;provider_status:Record<string,ProviderStatus>;simulated_rain:boolean;run_id:string;task_id:string;status:Status;revision:number;itinerary_version:number;parent_id:string|null;mode:string;poll_url:string;constraints:Constraint|null;needs_clarification?:boolean;missing_fields?:string[];questions:string[];itinerary:Itinerary|null;validation:{valid:boolean;issues:Issue[];confirmed_count?:number;blocking_confirmed_count?:number;unverified_count?:number;informational_count?:number;unverified_checks:string[];passed_checks:number;total_checks:number}|null;trace:Trace[];evidence:Evidence[];metrics:{agent_steps:Record<string,number>;tool_attempts:number;model_attempts:number;tokens:number|null;replanning_count:number};error:{code:string;message:string}|null}
export interface PlanInput {session_id?:string;product_features?:boolean;remember_preferences?:boolean;travel_preferences?:TravelPreferences;query:string;mode:'auto'|'fixture'|'live';demo:boolean;constraints?:Constraint;scenario?:'normal'|'rain'|'outage'|'transport'}

export interface TravelPreferences {travel_pace?:string|null;interests?:string[];transport_preference?:string|null;budget_level?:string|null;avoid_early_departure?:boolean|null;walking_tolerance?:string|null;accommodation_preferences?:string[]}
export interface Hotel extends Place {hotel_name:string;address:string|null;district:string|null;source:string;distance_meters:number|null;distance_kind:string;route:Route|null;station_route:Route|null}
export interface Accommodation {city:string;days:number[];recommended_area:string;reasons:string[];candidates:Hotel[];selected_hotel_id:string|null;disclaimer:string}
export interface Comparison {origin:string;destination:string;day:number;recommended_id:string|null;recommendation:string;candidates:{id:string;mode:string;provider_mode:string;departure:string;arrival:string;cost:number|null;transfers:number;estimate:{local_access_minutes:number|null;recommended_buffer_minutes:number;scheduled_duration_minutes:number;arrival_transfer_minutes:number|null;estimated_total_minutes:number|null;access_source:string}}[]}
